name: "Update Element Nightly"
on:
  schedule:
    - cron: "19 18 * * *"
  workflow_dispatch:

jobs:
  update-element-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Install Nu
        uses: hustcer/setup-nu@v3
      - name: Check version, grab date & sha256
        run: nu ./element-nightly/update.nu
      - name: Test Build
        run: nix build .#element-desktop-nightly
      - name: Push
        if: ${{ success() }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update Element Nightly"
